### PR TITLE
Add files to Support other Translation

### PR DESCRIPTION
**Pull request by shubhamlende**
Added translation files to support other languages.

let me know if any issue occurred or if any other way to do this thing.

### CODE REVIEW

**Comment by rsimon** [comment]
Many thanks for this. Yes, that's the right way. How did you do the translations? Was this done automatically? (I'm specifically wondering because we had a Greek translation already, and yours seems to differ.)

What do you mean with the `// translation missing` comment in `index.js`? Is this for cases where timeago.js doesn't have a translation available? (In this case, there should be no registration.)

**Comment by shubhamlende** [comment]
Hi,
I have used google translator to translate the descriptions. The //translation missing means timeago.js didn't support those languages.

**Comment by rsimon** [comment]
Thanks for this! I merged it into a work branch for now, and will make the necessary tweaks concerning the timeago.js.

**Comment by shubhamlende** [comment]
Hi,

I have one idea which will solved all the type of translation issues and we
don't need more to depends on this library for translation.

Instead of uses translation text from recogitio-client-core and we need to
pass language in Annotorious.init() method. Should we pass object{} which
directly use in showing text from this object.

This approach will solved the translation problem which will support all
type of translation text.

Example,

Annotorious.init({
local:{
"Okay":"okay",
.....
}
});

Let me know what you think about this approach.

Thanks,
Shubham

**Comment by rsimon** [comment]
Overriding the defaults from outside sounds like a good idea. The only issue I see is that some parts of the UI (as you have seen) are handled by the built-in localization from timeago.js. (I don't know whether it's possible to override this as well.)

**Comment by shubhamlende** [comment]
Hi,

We can handle such scenario where if user haven't provide any localisation
text in annotorious init method then it should use timego.js library
otherwise it will refer the text which user has provided.


Thanks & Regards,
shubham

**Pull request merged**
