### PR TITLE
Purpose dropdown

### PR DESCRIPTION
**Pull request by dnoneill**

### CODE REVIEW

**Comment by dnoneill** [comment]
@rsimon I could use some advice on how to set the purposes globally so I can access them in the comment widget and the purpose dropdown but otherwise I think it is ready to go.

**Comment by rsimon** [comment]
Modifiying the annotation "at the top level" (outside of the bodies) is, to be honest, not possible in the moment the way the editor architecture is set up. You can hack this in principle. My advice for now would be to introduce e.g. an `.onUpdateProperty(fieldName, obj)` callback that works like the `.onUpdateBody` callbacks, with the difference that `.onUpdateProperty` would add or replace a field at the top level of the annotation.

In the long run, though, I agree that a better mechanism for this is needed & the whole editor architecture needs a bit of rethinking + simplifying. (I think I also mentioned the problems associated with draft bodies vs. React's pattern of controlled components, which is evolving into a real pain point.) My schedule's a bit packed right now, but I'll try to think up a better design over the Christmas break.

**Comment by dnoneill** [comment]
@rsimon I am not talking about top level editing. I had define a list of purposes (commenting, describing, etc) in the two files and I had to define them in both files. I was wondering if there is a way to define that list of purposes globally instead of copying them into every component that needs them.

That is fine. Hope you have a good holiday.

**Comment by rsimon** [comment]
Ah, sorry. Understood. To avoid declaring them in two places, you could just declare them as an exported const once. E.g. in `PurposeDropdown`.

```js
export const purposes = [
  {'value': 'assessing', 'label': 'Assessing'}, 
  {'value': 'bookmarking', 'label': 'Bookmarking'}, 
  {'value': 'classifying', 'label': 'Classifying'}, 
  {'value': 'commenting', 'label': 'Commenting'}, 
  {'value': 'describing', 'label': 'Describing'},
  {'value': 'editing', 'label': 'Editing'},
  {'value': 'highlighting', 'label': 'Highlighting'},
  {'value': 'identifying', 'label': 'Identifying'},
  {'value': 'linking', 'label': 'Linking'},
  {'value': 'moderating', 'label': 'Moderating'},
  {'value': 'questioning', 'label': 'Questioning'}
];
```

Because its exported, you can just import into `CommentWidget`. E.g.

```js
import { purposes } from './PurposeDropdown';

// And then if you just need the values
const purposeValues = purposes.map(p => p.value);
```

**Comment by rsimon** [comment]
Many thanks for this! Some minor things don't seem to work perfectly yet. (E.g. the dropdown isn't available in the reply field. Only when I start typing, the dropdown is rendered. But when I change the purpose, the reply is deleted again.) But that relates to minor things with the React lifecycle and/or my general design issues with the editor that I mentioned earlier (and which I hope to rethink during the Christmas break.) 

Anyways: given that the feature is optional, I'm merging now & I'm happy to assist with ironing out the remaining tiny things.

**Comment by dnoneill** [comment]
@rsimon The dropdown only being available after something is entered was intentional. Because of the lifecycle of how an annotation is built it was necessary otherwise if you changed the dropdown the purpose would not update until text was entered. It was more expedient to not even allow the option until text was entered. 
And the second of course relates to the deletion of replies if the existing comment is edited. Sounds good. I will make sure to tweak these features if you update how the code works.

**Pull request merged**
