### PR TITLE
Add admin option

### PR DESCRIPTION
**Pull request by dnoneill**
Allows the option for user to add auth option that allows a admin user that can edit all annotations if "MINE_ONLY" is set.

```
anno.setAuthInfo({
  id: 'http://www.example.com/rainer',
   displayName: 'rainer',
   isAdmin: true
});
```

### CODE REVIEW

**Comment by rsimon** [comment]
What's the benefit of that over initializing the widget with the `editable: true` option when the current user is admin? I'd rather want to avoid application-specific concepts in the API.

**Comment by dnoneill** [comment]
@rsimon Not setting MINE_ONLY you mean? It is actually because I did not think of that lol. Thanks.

**Comment by rsimon** [comment]
Ah, got it. Yes :-) `MINE_ONLY` is only one option, you can also override fully to `true` or `false`.

**Comment by dnoneill** [comment]
@rsimon Yeah I was overthinking things and forgetting that is actually something I set. Thanks for your help. Made my fix a snap.

**Pull request closed without merging**
